# Site settings
title: Android Aplications
email: costea.bostan@gmail.com
description: This web site contains my Android applications and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://costeabostan.github.io/" # the base hostname & protocol for your site
twitter_username: Costea_Bostan
github_username:  costeabostan
comments: true
# Build settings
markdown: kramdown
